### ISSUE TITLE
Workflow Uses Moving Target Branch

### ISSUE THREAD

**Issue by tillmann-crabnebula** [mozilla/supply-chain#2]
Is there a specific reason for the workflow to target the master branch of the checkout action?
IMHO this moving target can break workflows and is prone to supply chain attacks this project aims to manage.

https://github.com/mozilla/supply-chain/blob/25149b2bee98e055c55b65c88d0d0fc238c04956/.github/workflows/aggregate.yml#L17

I am used to either using the release tag or a commit hash like:
```yml
    - uses: actions/checkout@v4
```

**Comment by bholley** [comment]
Fixed by #3.
